"""Focused UI helpers moved from the Streamlit entry point."""

from __future__ import annotations

from dnd_combat_simulator.ui.monolith import (
    GENERATED_SHARE_FINGERPRINT_KEY,
    GENERATED_SHARE_URL_KEY,
    INVALID_SHARED_CONFIG_MESSAGE_KEY,
    LOADED_SHARE_ID_KEY,
    LOADED_SHARED_CONFIG_MESSAGE_KEY,
    LOADED_SHARED_CONFIG_TOKEN_KEY,
    SHARE_ERROR_MESSAGE_KEY,
    _current_shared_configuration,
    _current_shared_configuration_url,
    _current_short_shared_configuration_url,
    _legacy_current_shared_configuration_url,
    _render_share_configuration_button,
    _resolution_type_label,
    _share_configuration_fingerprint,
    _successful_save_damage_label,
    get_streamlit_share_store,
    get_supabase_share_store_from_secrets,
    load_configuration_from_share_store,
    load_shared_configuration_from_query,
    resolve_shared_query_params,
    save_shared_configuration,
    share_store_ui_message,
)

__all__ = [
    "LOADED_SHARED_CONFIG_TOKEN_KEY",
    "LOADED_SHARE_ID_KEY",
    "GENERATED_SHARE_URL_KEY",
    "GENERATED_SHARE_FINGERPRINT_KEY",
    "SHARE_ERROR_MESSAGE_KEY",
    "LOADED_SHARED_CONFIG_MESSAGE_KEY",
    "INVALID_SHARED_CONFIG_MESSAGE_KEY",
    "_resolution_type_label",
    "_successful_save_damage_label",
    "share_store_ui_message",
    "resolve_shared_query_params",
    "get_supabase_share_store_from_secrets",
    "get_streamlit_share_store",
    "load_configuration_from_share_store",
    "load_shared_configuration_from_query",
    "save_shared_configuration",
    "_current_shared_configuration",
    "_current_short_shared_configuration_url",
    "_legacy_current_shared_configuration_url",
    "_current_shared_configuration_url",
    "_share_configuration_fingerprint",
    "_render_share_configuration_button",
]
